apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qa2tpd1ej-python
  janus-idp.io/tekton: qa2tpd1ej-python
  backstage.io/kubernetes-id: qa2tpd1ej-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qa2tpd1ej-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
